### PR TITLE
Added Push and Pull with local resources

### PR DESCRIPTION
**Pull request by ahmadalwareh**
## 👨‍💻 Changes proposed

- Added Push and Pull with local resources
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by ahmadalwareh** [comment]
Hey @Pradumnasaraf 
The merge request is corrected now and you can merge it safely.
Thanks!

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

Not sure why you are removing this command, any specific reason?

Screenshot 2022-12-13 at 11 34 28 AM

**Comment by ahmadalwareh** [comment]
> Hey,
> 
> Not sure why you are removing this command, any specific reason?
> 
> Screenshot 2022-12-13 at 11 34 28 AM

I think I drop it by mistake! it's back now, thanks for letting me know about it :D

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
