### PR TITLE
added docker overview in README

### PR DESCRIPTION
**Pull request by sumitNITS**
Hi @Pradumnasaraf,
The Docker README was starting with the Docker Images section, although there are learning resources provided in it but the short easy to understanding overview was kind of missing in that, adding it will be helpful for newcomers who are just starting with docker and coming for the first time to this repo for docker.

This is how it looks after adding the overview
docker overview

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/45"></a>

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

I think if you condense both points into 3-4 lines that will be good. I don't wan't too much text on the notes to scare people. Remove the headings as well.

Also, follow [Contributing Guidelines]( https://github.com/Pradumnasaraf/DevOps/blob/main/CONTRIBUTING.md) - Issue before PR.

**Comment by sumitNITS** [comment]
Hi @Pradumnasaraf, I am feeling that the text notes that I wrote in this PR are still very less, definitely this will not going to scare people out. When I was starting with docker or as a beginner when I start with any new stack I think of a few main points including "what is this tech", "why is this tech needed" & "How and where I can use this tech". Zipping all those things in mind I wrote it that way. Again, the present README is starting with the Images section and is not having the section that a curious newcomer brain really wants to know the flow of "What, Why, How, and Where".
We can compress it to 3-4 lines but then it will be incomplete for newcomers and eventually one has to google for something!

Please think of this once again, and let me know. 

Lastly, apologies for violating the contributing guidelines. I will keep that thing in mind!
I will wait for your response soon. Have a good day ahead!

**Comment by Pradumnasaraf** [comment]
I agree, by "scare people" I mean we have a short intro on other topics like k8s, actions etc. So when see it's too much info compared to other topics so mindset says "let's try different topics". Hope you got the thought

No worries, the solution is to add more details to topics :)

**Comment by Pradumnasaraf** [comment]
If you want to add the custom network command, add it. I will merge it then. Otherwise Looks good!

**Comment by sumitNITS** [comment]
@Pradumnasaraf  I've added the create custom network command, you can check and verify now! 😊

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by sumitNITS** [comment]
Thanks to you too @Pradumnasaraf 
Looking forward to contribute more 🤝

**Pull request merged**
