### PR TITLE
Docker commands updated with tips

### PR DESCRIPTION
**Pull request by sumitNITS**
Hi @Pradumnasaraf,
I've added the command to create the network and the tips at the bottom.
Thanks, and have a good day ahead!

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/DevOps/pull/48"></a>

### CODE REVIEW

**Review by Pradumnasaraf — COMMENTED** [review]
Hey,

There are duplicated elements from #47 **Tips and Short hands** changes are not needed. Also, you can add the below to your existing opened PR #45 

```bash
docker network create <network-name>
```

Closing this one!

**Comment by sumitNITS** [comment]
Alright @Pradumnasaraf, actually my thought process before adding that command was in the docker commands networking section "Run a container on a certain network/own created network" is using our own custom <network-name> to run the container, But before that, there is a need to create that custom <network-name> and it was missing so thinking that way I did send this PR.
Have a good day ahead!

**Comment by Pradumnasaraf** [comment]
Hey, this why I said above to add that custom network creation command in #45 :)

**Comment by sumitNITS** [comment]
Okay done. Added in #45

**Pull request closed without merging**
